server:
  port: 8082

spring:
  application:
    name: delivery-partner-B
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      group-id: delivery-partner-group
